name: Build Electron app

on:
  push:
    tags:
      - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run check
        run: |
          npm install
          npm run check

  create-release:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create release
        run: |
          tag_name="${GITHUB_REF##*/}"
          hub release create -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: create-release

    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build
        run: |
          npm install
          npm run build
          npm run dist

      - name: Release
        shell: pwsh
        run: |
          $tagName = ${env:GITHUB_REF} -replace "refs/tags/", ""
          $assets = @()

          Get-ChildItem ./out -File | 
          Foreach-Object {
            $assets += "-a ./out/" + $_.Name
          }

          Get-Location
          Get-ChildItem

          hub release edit $assets -m $tagName $tagName
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
